### ISSUE TITLE
Incompatibility with The Aether Reborn

### ISSUE THREAD

**Issue by CapoFantasma97** [Wesley1808/ServerCore#6] opened 2021-12-01 13:35 UTC
I'm not sure what to look for. I updated a number of mods, and the pack only crashes on startup when ServerCore stays in it.

**Versions**
ServerCore: 1.2.5
Minecraft: 1.17.1
Fabric version: 0.12.8

**Mod incompatibilities**
ServerCore is clearly compatible with the recent 0.12.8 Fabric update, I ran an instance with just ServerCore and it works fine.

**Logs** https://gist.github.com/CapoFantasma97/116661e9ed598c45a9073df2ea948ede
No crash report has been generated. I only have logs which are deobfuscated by NotEnoughCrashes.

**Comment by Wesley1808** [comment] 2021-12-01 14:31
Hi, thank you for reporting this issue!
This seems to be caused by an incompatibility with The Aether Reborn mod.

ServerCore contains a patch that stops maps from loading chunks (causing lagspikes), which can be seen [here](https://github.com/Wesley1808/ServerCore-Fabric/blob/1.18/src/main/java/org/provim/servercore/mixin/optimizations/chunk_loading/MapItemMixin.java).
The Aether Reborn seems to [mixin override the entire method](https://github.com/devs-immortal/Paradise-Lost/blob/1.17/src/main/java/net/id/aether/mixin/item/FilledMapMixin.java), making basically any mod touching player held map functionality at all - incompatible, causing crashes.

**Comment by CapoFantasma97** [comment] 2021-12-01 16:51
I opened an issue at devs-immortal/Paradise-Lost/issues/562 relaying the findings and isolating the affected mods.
Hopefully the Aether Reborn's devs will resolve it soon.

**Comment by Wesley1808** [comment] 2022-01-08 21:22
This issue has been resolved in version 1.2.7 for 1.18.1.
Is this still required on 1.17?

**Comment by Wesley1808** [comment] 2022-01-16 12:19
Closed due to inactivity.

Please make another comment on this issue if you still need this to be fixed in the 1.17 version of the game, which would require a bit more effort to do. 
Due to other potential bugs / issues its highly recommended to use the 1.18 version, if possible.

**Closed by Wesley1808** 2022-01-16 12:19 UTC

**Comment by Jack-Papel** [comment] 2022-02-08 05:40
This has been resolved internally on our end, and will be in our next release, which is coming on the 14th. Thanks for being patient.
