### ISSUE TITLE
1.19 status command not replacing %{key}%

### ISSUE THREAD

**Issue by MrJoshuaT** [Wesley1808/ServerCore#32] opened 2022-06-09 19:26 UTC
**Describe the bug**
The `/servercore status` command is not working in-game, it doesn't respond with a chat messageto the command and produces no errors. In the console doing `/servercore status` it produces e.g. %VIEW_DISTANCE% etc instead of the value

Example output from console.
/servercore status
[21:16:02] [Server thread/INFO]:  ServerCore 
>----( ServerCore )----<
>> Chunk-Tick Distance: %CHUNK_TICK_DISTANCE%
>> Simulation Distance: %SIMULATION_DISTANCE%
>> View Distance: %VIEW_DISTANCE%
>> Mobcap Multiplier: %MOBCAPS%

**Reproduce**
Install latest `servercore-1.3.0-1.19.jar` from modrinth into a 1.19 world. Type into game and console `/servercore status`.

**Expected behavior**
Typing the command in chat should respond with a response chat message. Doing `/servercore status` should replace the %{key}% values with their actual value.

**Versions** -Latest is not a version!
ServerCore: 1.3.0-1.19
Minecraft: 1.19

**Mod incompatibilities**
Cannot see any other mods that would cause this. Mods listed below:
* carpet-extra
* EditSign
* fabric-carpet
* InvView
* ledger
* servercore
* starlight
* voicechat

**Comment by Wesley1808** [comment] 2022-06-10 07:09
Delete the [commands] section in the config.
Duplicate of: #30

**Closed by Wesley1808** 2022-06-10 07:09 UTC
