### ISSUE TITLE
Servercore Breaks FTBEssentials `/rtp` command

### ISSUE THREAD

**Issue by Aiidoneus** [Wesley1808/ServerCore#69] opened 2023-08-05 20:47 UTC
**Describe the bug**
As soon as I install servercore on the server, it breaks FTB-Essentials `/rtp` command. It doesn't crash or anything like that but when trying to run the `/rtp` command, is immediatly returns saying "Could not find a valid location to teleport to."

**Reproduce**
Install servercore on a server with FTB-Essentials

**Expected behavior**
RTP command to teleport properly

**Versions** -Latest is not a version!
ServerCore: 1.3.5
Minecraft: 1.19.2

**Comment by Wesley1808** [comment] 2023-08-05 22:20
Does this still happen when you set `optimizations.reduce_sync_loads` to false?
And is this on Forge or Fabric?

**Comment by Wesley1808** [comment] 2023-08-05 22:26
Oh wait, this is a duplicate of #62, which was fixed with commit https://github.com/Wesley1808/ServerCore/commit/03c993e9b3823d63b39e999c7d9cb5c4f946b01f
I will probably backport 1.3.7 to 1.19.2 soon since its still used in a lot of modpacks.

**Comment by Aiidoneus** [comment] 2023-08-06 00:55
Oh sorry.i didn't realize that was the same issue? We don't crash at all, but just error out. So I wasn't sure it was related

**Comment by Wesley1808** [comment] 2023-08-06 06:23
The results are indeed a bit different, but there's a very high chance its caused by the same patch. I haven't noticed anything else that could cause that and it was more of a freeze / lag issue then an actual crash (crash caused by watchdog for taking too long), which can be affected by the configuration of the RTP.

I might be wrong about this since I haven't actually had the time yet to properly test this (apologies if I'm wrong), but if you want to give it a try you can remove the line `"optimizations.tickets.ServerLevelMixin"`, in `servercore.common.mixins.json` inside the .jar file.

**Comment by Aiidoneus** [comment] 2023-08-06 13:59
Yeah. I just tried removing that and it did indeed fix the issue!

**Comment by katubug** [comment] 2024-05-27 19:59
> Oh wait, this is probably a duplicate of #62 with different configuration which was fixed with commit [03c993e](https://github.com/Wesley1808/ServerCore/commit/03c993e9b3823d63b39e999c7d9cb5c4f946b01f) I will probably backport 1.3.7 to 1.19.2 soon since its still used in a lot of modpacks.

Hi, we're experiencing a freezing issue with rtp on our server for the Cottage Witch modpack on 1.19.2, did this fix get backported? Thanks for your time!

**Comment by Wesley1808** [comment] 2024-05-27 22:55
Apologies, must have forgotten to backport it. Probably won't make a release for it, but you'll be able to download it from github actions [here.](https://github.com/Wesley1808/ServerCore/actions/runs/9260998076)

**Closed by Wesley1808** 2024-05-27 22:55 UTC

**Comment by katubug** [comment] 2024-05-27 22:58
I'm guessing doing that won't allow me to export the mod with my Curseforge
modpack? Thank you btw!

**Comment by Wesley1808** [comment] 2024-05-27 23:04
You should be able to run it by simply adding it to your server - adding external files only on the server shouldn't be much of a problem as far as I know. Exporting the mod with a curseforge modpack probably won't work, as I would assume that requires the file to be uploaded there.

**Comment by katubug** [comment] 2024-05-27 23:15
Gotcha, that sounds right. Thank you!

**Comment by katubug** [comment] 2024-08-09 16:02
> You should be able to run it by simply adding it to your server - adding external files only on the server shouldn't be much of a problem as far as I know. Exporting the mod with a curseforge modpack probably won't work, as I would assume that requires the file to be uploaded there.

Hi, sorry to necro this thread - would you consider making this an official curseforge release for the 1.19.2 version? I want to recommend people install servercore, but the github actions file is no longer available, and it would be a lot easier for the end user if it was on curseforge. I appreciate you taking the time to read this, regardless.
